import {
  CHATGPT_PLAN_MODELS,
  DEFAULT_AGENT_MODELS,
  PROVIDER_LABELS,
} from "@/agent/provider-catalog";
import type { AuthProvider } from "@/features/integrations/types";

const GG_AI_API_KEY_PROVIDERS: AuthProvider[] = [
  {
    key: "anthropic",
    label: PROVIDER_LABELS.anthropic,
    description: "Connect Claude so the AI assistant can write for you.",
    methods: ["api_key", "oauth"],
    defaultMethod: "api_key",
    scopes: [],
    models: [DEFAULT_AGENT_MODELS.anthropic],
    secretLabel: "Anthropic API key or OAuth token",
    docsUrl: "https://docs.anthropic.com/",
  },
  {
    key: "xiaomi",
    label: PROVIDER_LABELS.xiaomi,
    description: "Connect Xiaomi MiMo so the AI assistant can write for you.",
    methods: ["api_key"],
    defaultMethod: "api_key",
    scopes: [],
    models: [DEFAULT_AGENT_MODELS.xiaomi],
    secretLabel: "Xiaomi MiMo API key",
    docsUrl: "https://mimo.xiaomi.com/",
  },
  {
    key: "openai",
    label: PROVIDER_LABELS.openai,
    description: "Connect OpenAI so the AI assistant can write for you.",
    methods: ["api_key", "oauth"],
    defaultMethod: "api_key",
    scopes: [],
    models: [DEFAULT_AGENT_MODELS.openai, "gpt-4.1", ...CHATGPT_PLAN_MODELS],
    secretLabel: "OpenAI API key",
    docsUrl: "https://platform.openai.com/docs",
  },
  {
    key: "gemini",
    label: PROVIDER_LABELS.gemini,
    description:
      "Connect Gemini Code Assist so the AI assistant can write for you.",
    methods: ["api_key"],
    defaultMethod: "api_key",
    scopes: [],
    models: [DEFAULT_AGENT_MODELS.gemini],
    secretLabel: "Gemini Code Assist access token",
    docsUrl: "https://ai.google.dev/gemini-api/docs",
  },
  {
    key: "glm",
    label: PROVIDER_LABELS.glm,
    description: "Connect Z.AI / GLM so the AI assistant can write for you.",
    methods: ["api_key"],
    defaultMethod: "api_key",
    scopes: [],
    models: [DEFAULT_AGENT_MODELS.glm],
    secretLabel: "Z.AI / GLM API key",
    docsUrl: "https://docs.z.ai/",
  },
  {
    key: "moonshot",
    label: PROVIDER_LABELS.moonshot,
    description: "Connect Moonshot so the AI assistant can write for you.",
    methods: ["api_key"],
    defaultMethod: "api_key",
    scopes: [],
    models: [DEFAULT_AGENT_MODELS.moonshot],
    secretLabel: "Moonshot API key",
    docsUrl: "https://platform.moonshot.ai/docs",
  },
  {
    key: "deepseek",
    label: PROVIDER_LABELS.deepseek,
    description: "Connect DeepSeek so the AI assistant can write for you.",
    methods: ["api_key"],
    defaultMethod: "api_key",
    scopes: [],
    models: [DEFAULT_AGENT_MODELS.deepseek],
    secretLabel: "DeepSeek API key",
    docsUrl: "https://api-docs.deepseek.com/",
  },
  {
    key: "openrouter",
    label: PROVIDER_LABELS.openrouter,
    description: "Connect OpenRouter so the AI assistant can write for you.",
    methods: ["api_key"],
    defaultMethod: "api_key",
    scopes: [],
    models: [DEFAULT_AGENT_MODELS.openrouter],
    secretLabel: "OpenRouter API key",
    docsUrl: "https://openrouter.ai/docs",
  },
  {
    key: "sakana",
    label: PROVIDER_LABELS.sakana,
    description: "Connect Sakana so the AI assistant can write for you.",
    methods: ["api_key"],
    defaultMethod: "api_key",
    scopes: [],
    models: [DEFAULT_AGENT_MODELS.sakana],
    secretLabel: "Sakana API key",
    docsUrl: "https://sakana.ai/",
  },
  {
    key: "minimax",
    label: PROVIDER_LABELS.minimax,
    description: "Connect MiniMax so the AI assistant can write for you.",
    methods: ["api_key"],
    defaultMethod: "api_key",
    scopes: [],
    models: [DEFAULT_AGENT_MODELS.minimax],
    secretLabel: "MiniMax API key",
    docsUrl: "https://www.minimax.io/platform/document",
  },
];

export const AUTH_PROVIDERS: AuthProvider[] = [
  ...GG_AI_API_KEY_PROVIDERS,
  {
    key: "custom",
    label: PROVIDER_LABELS.custom,
    description: "Use your own OpenAI-compatible AI service (advanced).",
    methods: ["api_key"],
    defaultMethod: "api_key",
    scopes: [],
    models: [DEFAULT_AGENT_MODELS.custom],
    secretLabel: "Access key",
    docsUrl: "https://platform.openai.com/docs/api-reference",
  },
  {
    key: "linkedin",
    label: PROVIDER_LABELS.linkedin,
    description:
      "Connect your LinkedIn account. Nothing is posted or commented without your OK.",
    methods: ["oauth"],
    defaultMethod: "oauth",
    scopes: [
      "openid",
      "profile",
      "email",
      "w_member_social",
      "w_member_social_feed",
      "r_member_social_feed",
    ],
    models: [],
    secretLabel: "LinkedIn OAuth",
    docsUrl:
      "https://learn.microsoft.com/linkedin/shared/authentication/authorization-code-flow",
  },
];

export function getAuthProvider(key: string): AuthProvider | null {
  return AUTH_PROVIDERS.find((provider) => provider.key === key) ?? null;
}
